train_script: /content/diffusers/examples/text_to_image/train_text_to_image_lora_sdxl.py

pretrained_model_name_or_path: stabilityai/stable-diffusion-xl-base-1.0
pretrained_vae_model_name_or_path: madebyollin/sdxl-vae-fp16-fix
train_data_dir: /content/Text-to-Image-Pixel-Art/data/train_corrective
output_dir: /content/drive/MyDrive/pixelart-lora-output-corrective-ckpt8000

resolution: 1024
image_interpolation_mode: nearest
train_batch_size: 2
gradient_accumulation_steps: 8
learning_rate: 0.00003
max_train_steps: 1500
checkpointing_steps: 250
checkpoints_total_limit: 8
rank: 16
seed: 42
snr_gamma: 5.0
validation_prompt: pixel art, single centered knight icon, red cape, silver sword, shield, crisp edges
validation_epochs: 1
num_validation_images: 4
mixed_precision: bf16
lr_scheduler: constant
lr_warmup_steps: 0
dataloader_num_workers: 4
max_grad_norm: 1.0

gradient_checkpointing: true
allow_tf32: true
enable_xformers_memory_efficient_attention: false
train_text_encoder: false
use_8bit_adam: false

resume_from_checkpoint: /content/drive/MyDrive/pixelart-lora-output/checkpoint-8000
